// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement;

import java.lang.String;
import javax.vecmath.Vector3d;
import simbad.sim.SensorMatrix;

/************************************************************/
/**
 * 
 */
public class Image {
	/**
	 * 
	 */
	private SensorMatrix imageData;
	/**
	 * 
	 */
	private double direction;
	/**
	 * 
	 */
	private String originName;
	/**
	 * 
	 */
	private Vector3d location;

	/**
	 * 
	 * @param imageData 
	 * @param direction 
	 * @param originName 
	 * @param location 
	 */
	public Image(SensorMatrix imageData, double direction, String originName, Vector3d location) {

		this.imageData = imageData;
		this.direction = direction;
		this.originName = originName;
		this.location = location;
	}

	/**
	 * 
	 * @return 
	 */
	public SensorMatrix getImageData() {

		return imageData;
	}

	/**
	 * 
	 * @return 
	 */
	public double getDirection() {

		return direction;
	}

	/**
	 * 
	 * @return 
	 */
	public String getOrigin() {

		return originName;
	}

	/**
	 * 
	 * @return 
	 */
	public Vector3d getLocation() {

		return location;
	}
};
