// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement;

import java.lang.String;
import javax.vecmath.Vector3d;

/************************************************************/
/**
 * 
 */
public class Message {
	/**
	 * 
	 */
	private String data;
	/**
	 * 
	 */
	private String originName;
	/**
	 * 
	 */
	private Vector3d originLocation;
	/**
	 * 
	 */
	private int receiveDate;

	/**
	 * 
	 * @param data 
	 * @param originName 
	 * @param originLocation 
	 * @param receiveDate 
	 */
	public Message(String data, String originName, Vector3d originLocation, int receiveDate) {

		this.data = data;
		this.originName = originName;
		this.originLocation = originLocation;
		this.receiveDate = receiveDate;
	}

	/**
	 * 
	 * @return 
	 */
	public String getData() {

		return data;
	}

	/**
	 * 
	 * @return 
	 */
	public String getOriginName() {

		return originName;
	}

	/**
	 * 
	 * @return 
	 */
	public Vector3d getOriginLocation() {

		return originLocation;
	}

	/**
	 * 
	 * @return 
	 */
	public int getReceiveDate() {

		return receiveDate;
	}
};
