// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement;

import RootElement.UpdateStatus;

/************************************************************/
/**
 * 
 */
public interface Observer {
	/**
	 * 
	 * @param input 
	 */
	public void updateStatus(UpdateStatus input);

	/**
	 * 
	 * @param i 
	 */
	public void updateMission(int i);
};
