// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement;

import RootElement.ControlCenter;import RootElement.Observer;
import java.lang.String;
import java.util.concurrent.locks.ReentrantLock;
import javax.vecmath.Color3f;

/************************************************************/
/**
 * 
 */
public interface Robot extends Observer {
	/**
	 * 
	 * @param color3f 
	 */
	public void setColor(Color3f color3f);

	/**
	 * 
	 * @param controlCenter 
	 */
	public void setSupervisor(ControlCenter controlCenter);

	/**
	 * 
	 * @param lock 
	 */
	public void changeLock(ReentrantLock lock);

	/**
	 * 
	 * @return 
	 */
	public String getName();
};
